### ISSUE TITLE
Iterator stops in the middle

### ISSUE THREAD

**Issue by cecton** [CasualX/lde#11]
Great lib! Thanks!!

I've been testing your library on a Windows binary (PE) and I noticed that depending where I start the iteration in the buffer I don't have the same number of iterations.

I would have expected that if I start at 0x600 (where the opcodes seem to start) I would iterate until the end of the file (size=67MB) but I got less iterations than if I start at some other places that was of interest for me.

I have the feeling the iteration stops when it encounters something it doesn't understand OR maybe there is something I don't understand about the use of this library itself. Am I correct to think that the point of the iter function is to read the buffer to the end and provide an opcode for every iteration? Or am I wrong? (might sounds like a stupid question but I'm a beginner on this)

I don't mind writing some small code to help to debug. I'm not blocked by this issue but I'm interested to know more and participate on the development.

**Comment by CasualX** [comment]
Hello and thanks for taking interest!

---

A windows binary (PE file) contains more than just code instructions, you cannot simply start at some point and iterate until the end. This very simple length disassembler will stop when it encounters an instruction it does not understand.

You may try to extract the 'code' section of the PE file, using eg. [pelite](https://github.com/CasualX/pelite) whose job it is to parse the PE file structures (disclaimer: I am the author of pelite). You can use that library to extract the code section (assuming x64):

```rust
use pelite::pe64::{Pe, PeFile};

let map = pelite::FileMap::open("demo/Demo64.dll").unwrap();
let file = PeFile::from_bytes(&map).unwrap();
let code_section = file.section_headers().iter().find(|sect| &sect.Name == b".text\0\0\0").unwrap();
let code_bytes = file.get_section_bytes(code_section).unwrap();
for (opcode, va) in lde::X64.iter(code_bytes, code_section.VirtualAddress as u64) {
	println!("{:#x}: {}", va, opcode);
}
```

However even this isn't guaranteed to only contain executable code! jump tables for switch statements will put their tables in the code section as well as you can easily write source code in C++ or Rust which puts arbitrary data in the code section.

How to work around this issue depends on what your goal is. Here is an [example](https://github.com/CasualX/pelite/blob/master/examples/csgo/weapondata.rs#L70) where I'm looking for a particular bit of code which I know ahead of time what its structure is going to be, then I run through it with lde to find specific instructions which reveal the underlying data structures of the source code which generated that code.

---

I haven't found much time to work on this library in particular, I'd love to put more work into it (eg. supporting the new `v` -style sse instructions) but it should keep working for 32-bit and older x64 based instructions.

**Comment by cecton** [comment]
If I understand correctly, using pelite won't work either because there is no guarantee there will be only executable code.

What you suggest is, for example, to look for a particular piece of code and then run lde from there, am I correct?

I think that's what I have done so I will keep my approach to the problem as it is now then. I guess I was looking for a wrong abstraction. (The code is [here](https://github.com/cecton/patch-ultrawide-the-outer-worlds/blob/master/src/main.rs#L9) if you want to check.)
